# Generated by Django 3.0.8 on 2020-08-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('wltaddr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gamestate', models.CharField(max_length=1000)),
            ],
        ),
    ]
